"""Adding section to settings

Revision ID: 19c8a92553d6
Revises: 508568dd8957
Create Date: 2014-06-08 17:49:17.714667

"""

# revision identifiers, used by Alembic.
revision = '19c8a92553d6'
down_revision = '508568dd8957'

from alembic import op
import sqlalchemy as sa

# from impression.models import Setting

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('section', sa.VARCHAR(length=128), server_default='main', nullable=False))
    ### end Alembic commands ###
    # Setting(name='email-to', section='contact-form', vartype='str', system=True).insert()
    # Setting(name='email-from', section='contact-form', vartype='str', system=True).insert()
    # Setting(name='email-subject', section='contact-form', vartype='str', system=True).insert()
    # Setting(name='email-cc', section='contact-form', vartype='str', system=True).insert()
    # Setting(name='email-bcc', section='contact-form', vartype='str', system=True).insert()
    # Setting(name='smtp-server', section='contact-form', vartype='str', system=True).insert()
    # Setting(name='smtp-port', section='contact-form', vartype='str', system=True).insert()
    # Setting(name='smtp-ssl', section='contact-form', vartype='str', system=True).insert()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'section')
    ### end Alembic commands ###
