"""empty message

Revision ID: 436984fa80e4
Revises: None
Create Date: 2014-04-08 10:34:11.794017

"""

# revision identifiers, used by Alembic.
revision = '436984fa80e4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('int', 'str', 'bool', 'float'), nullable=False),
    sa.Column('allowed', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_types',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('openid', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('admin', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('key', sa.VARCHAR(length=512), nullable=True),
    sa.Column('name', sa.VARCHAR(length=512), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('role_type_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_type_id'], ['role_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('action', sa.VARCHAR(length=5120), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), nullable=True),
    sa.Column('url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=512), nullable=True),
    sa.Column('url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages')
    op.drop_table('posts')
    op.drop_table('logs')
    op.drop_table('user_roles')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('role_types')
    op.drop_table('settings')
    ### end Alembic commands ###
