"""Adding theme to content

Revision ID: 964f61695f01
Revises: 19c8a92553d6
Create Date: 2016-07-20 11:40:39.413798

"""

# revision identifiers, used by Alembic.
revision = '964f61695f01'
down_revision = '19c8a92553d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('theme', sa.VARCHAR(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'theme')
    ### end Alembic commands ###
